// <auto-generated />
using System;
using FactHarbor.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FactHarbor.Api.Migrations
{
    [DbContext(typeof(FhDbContext))]
    partial class FhDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("FactHarbor.Api.Data.ClaimSelectionDraftEntity", b =>
                {
                    b.Property<string>("DraftId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveInputType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveInputValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftAccessTokenHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftStateJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalJobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InviteCode")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastEventMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalInputType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalInputValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PipelineVariant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestartCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RestartedViaOther")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectionMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("DraftId");

                    b.HasIndex("Status");

                    b.ToTable("ClaimSelectionDrafts");
                });

            modelBuilder.Entity("FactHarbor.Api.Data.ClaimSelectionDraftEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterStatus")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeStatus")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TsUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DraftId", "Id");

                    b.ToTable("ClaimSelectionDraftEvents");
                });

            modelBuilder.Entity("FactHarbor.Api.Data.InviteCodeEntity", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DailyLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("HourlyLimit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxJobs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsedJobs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Code");

                    b.ToTable("InviteCodes");
                });

            modelBuilder.Entity("FactHarbor.Api.Data.InviteCodeUsageEntity", b =>
                {
                    b.Property<string>("InviteCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("InviteCode", "Date");

                    b.HasIndex("InviteCode");

                    b.ToTable("InviteCodeUsage");
                });

            modelBuilder.Entity("FactHarbor.Api.Data.JobEntity", b =>
                {
                    b.Property<string>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimSelectionDraftId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimSelectionJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Confidence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutedWebGitCommitHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitCommitHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputPreview")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("InputValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InviteCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentJobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PipelineVariant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreparedStage1Json")
                        .HasColumnType("TEXT");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PromptContentHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PromptLoadedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportMarkdown")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RetriedFromUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RetryReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TruthPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerdictLabel")
                        .HasColumnType("TEXT");

                    b.HasKey("JobId");

                    b.HasIndex("ClaimSelectionDraftId")
                        .IsUnique();

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("FactHarbor.Api.Data.JobEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TsUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "Id");

                    b.ToTable("JobEvents");
                });

            modelBuilder.Entity("FactHarbor.Api.Models.AnalysisMetrics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MetricsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("JobId");

                    b.ToTable("AnalysisMetrics");
                });

            modelBuilder.Entity("FactHarbor.Api.Models.AnalysisMetrics", b =>
                {
                    b.HasOne("FactHarbor.Api.Data.JobEntity", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });
#pragma warning restore 612, 618
        }
    }
}
